#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-parallel-executor
Version  : 0.2.2
Release  : 4
URL      : https://files.pythonhosted.org/packages/1e/05/09c2e7d81400072c786c4facb7838e9a0eca4e0fb491878c587c3764c45b/colcon-parallel-executor-0.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/1e/05/09c2e7d81400072c786c4facb7838e9a0eca4e0fb491878c587c3764c45b/colcon-parallel-executor-0.2.2.tar.gz
Summary  : Extension for colcon to process packages in parallel.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-parallel-executor-python3
Requires: colcon-parallel-executor-python
Requires: colcon-core
BuildRequires : buildreq-distutils3

%description
========================

%package python
Summary: python components for the colcon-parallel-executor package.
Group: Default
Requires: colcon-parallel-executor-python3

%description python
python components for the colcon-parallel-executor package.


%package python3
Summary: python3 components for the colcon-parallel-executor package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-parallel-executor package.


%prep
%setup -q -n colcon-parallel-executor-0.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535549305
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
